#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnguzApp.ContextoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="innguz_ventas")]
	public partial class Base_DatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertVentas(Ventas instance);
    partial void UpdateVentas(Ventas instance);
    partial void DeleteVentas(Ventas instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertTipo_Producto(Tipo_Producto instance);
    partial void UpdateTipo_Producto(Tipo_Producto instance);
    partial void DeleteTipo_Producto(Tipo_Producto instance);
    partial void InsertCategorias(Categorias instance);
    partial void UpdateCategorias(Categorias instance);
    partial void DeleteCategorias(Categorias instance);
    partial void InsertEstados_Periodo(Estados_Periodo instance);
    partial void UpdateEstados_Periodo(Estados_Periodo instance);
    partial void DeleteEstados_Periodo(Estados_Periodo instance);
    #endregion
		
		public Base_DatosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["innguz_ventasConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Base_DatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Base_DatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Base_DatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Base_DatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ventas> Ventas
		{
			get
			{
				return this.GetTable<Ventas>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_Producto> Tipo_Producto
		{
			get
			{
				return this.GetTable<Tipo_Producto>();
			}
		}
		
		public System.Data.Linq.Table<Categorias> Categorias
		{
			get
			{
				return this.GetTable<Categorias>();
			}
		}
		
		public System.Data.Linq.Table<Estados_Periodo> Estados_Periodo
		{
			get
			{
				return this.GetTable<Estados_Periodo>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_modificar_usuario")]
		public ISingleResult<SP_modificar_usuarioResult> SP_modificar_usuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string posicion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string clave, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary foto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_registro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, usuario, nombre, apellido, posicion, telefono, correo, clave, foto, fecha_registro);
			return ((ISingleResult<SP_modificar_usuarioResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ventas")]
	public partial class Ventas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Descripcion;
		
		private int _Cantidad;
		
		private decimal _Monto;
		
		private decimal _IVA;
		
		private decimal _Total;
		
		private System.Nullable<int> _Usuario_id;
		
		private System.Nullable<int> _Producto_Servicio_id;
		
		private System.Nullable<int> _periodo_id;
		
		private System.Nullable<System.DateTime> _FechaInserta;
		
		private string _UsuarioInserta;
		
		private System.Nullable<System.DateTime> _FechaActualiza;
		
		private string _UsuarioActualiza;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    partial void OnMontoChanging(decimal value);
    partial void OnMontoChanged();
    partial void OnIVAChanging(decimal value);
    partial void OnIVAChanged();
    partial void OnTotalChanging(decimal value);
    partial void OnTotalChanged();
    partial void OnUsuario_idChanging(System.Nullable<int> value);
    partial void OnUsuario_idChanged();
    partial void OnProducto_Servicio_idChanging(System.Nullable<int> value);
    partial void OnProducto_Servicio_idChanged();
    partial void Onperiodo_idChanging(System.Nullable<int> value);
    partial void Onperiodo_idChanged();
    partial void OnFechaInsertaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaInsertaChanged();
    partial void OnUsuarioInsertaChanging(string value);
    partial void OnUsuarioInsertaChanged();
    partial void OnFechaActualizaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaActualizaChanged();
    partial void OnUsuarioActualizaChanging(string value);
    partial void OnUsuarioActualizaChanged();
    #endregion
		
		public Ventas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(4,2) NOT NULL")]
		public decimal Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this.OnMontoChanging(value);
					this.SendPropertyChanging();
					this._Monto = value;
					this.SendPropertyChanged("Monto");
					this.OnMontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IVA", DbType="Decimal(4,2) NOT NULL")]
		public decimal IVA
		{
			get
			{
				return this._IVA;
			}
			set
			{
				if ((this._IVA != value))
				{
					this.OnIVAChanging(value);
					this.SendPropertyChanging();
					this._IVA = value;
					this.SendPropertyChanged("IVA");
					this.OnIVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(4,2) NOT NULL")]
		public decimal Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_id", DbType="Int")]
		public System.Nullable<int> Usuario_id
		{
			get
			{
				return this._Usuario_id;
			}
			set
			{
				if ((this._Usuario_id != value))
				{
					this.OnUsuario_idChanging(value);
					this.SendPropertyChanging();
					this._Usuario_id = value;
					this.SendPropertyChanged("Usuario_id");
					this.OnUsuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto_Servicio_id", DbType="Int")]
		public System.Nullable<int> Producto_Servicio_id
		{
			get
			{
				return this._Producto_Servicio_id;
			}
			set
			{
				if ((this._Producto_Servicio_id != value))
				{
					this.OnProducto_Servicio_idChanging(value);
					this.SendPropertyChanging();
					this._Producto_Servicio_id = value;
					this.SendPropertyChanged("Producto_Servicio_id");
					this.OnProducto_Servicio_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periodo_id", DbType="Int")]
		public System.Nullable<int> periodo_id
		{
			get
			{
				return this._periodo_id;
			}
			set
			{
				if ((this._periodo_id != value))
				{
					this.Onperiodo_idChanging(value);
					this.SendPropertyChanging();
					this._periodo_id = value;
					this.SendPropertyChanged("periodo_id");
					this.Onperiodo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInserta", DbType="Date")]
		public System.Nullable<System.DateTime> FechaInserta
		{
			get
			{
				return this._FechaInserta;
			}
			set
			{
				if ((this._FechaInserta != value))
				{
					this.OnFechaInsertaChanging(value);
					this.SendPropertyChanging();
					this._FechaInserta = value;
					this.SendPropertyChanged("FechaInserta");
					this.OnFechaInsertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioInserta", DbType="VarChar(50)")]
		public string UsuarioInserta
		{
			get
			{
				return this._UsuarioInserta;
			}
			set
			{
				if ((this._UsuarioInserta != value))
				{
					this.OnUsuarioInsertaChanging(value);
					this.SendPropertyChanging();
					this._UsuarioInserta = value;
					this.SendPropertyChanged("UsuarioInserta");
					this.OnUsuarioInsertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualiza", DbType="Date")]
		public System.Nullable<System.DateTime> FechaActualiza
		{
			get
			{
				return this._FechaActualiza;
			}
			set
			{
				if ((this._FechaActualiza != value))
				{
					this.OnFechaActualizaChanging(value);
					this.SendPropertyChanging();
					this._FechaActualiza = value;
					this.SendPropertyChanged("FechaActualiza");
					this.OnFechaActualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioActualiza", DbType="VarChar(50)")]
		public string UsuarioActualiza
		{
			get
			{
				return this._UsuarioActualiza;
			}
			set
			{
				if ((this._UsuarioActualiza != value))
				{
					this.OnUsuarioActualizaChanging(value);
					this.SendPropertyChanging();
					this._UsuarioActualiza = value;
					this.SendPropertyChanged("UsuarioActualiza");
					this.OnUsuarioActualizaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Usuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Posicion;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _Clave;
		
		private System.Data.Linq.Binary _Foto;
		
		private System.DateTime _Fecha_registro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnPosicionChanging(string value);
    partial void OnPosicionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnClaveChanging(string value);
    partial void OnClaveChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    partial void OnFecha_registroChanging(System.DateTime value);
    partial void OnFecha_registroChanged();
    #endregion
		
		public Usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posicion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Posicion
		{
			get
			{
				return this._Posicion;
			}
			set
			{
				if ((this._Posicion != value))
				{
					this.OnPosicionChanging(value);
					this.SendPropertyChanging();
					this._Posicion = value;
					this.SendPropertyChanged("Posicion");
					this.OnPosicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this.OnClaveChanging(value);
					this.SendPropertyChanging();
					this._Clave = value;
					this.SendPropertyChanged("Clave");
					this.OnClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_registro", DbType="Date NOT NULL")]
		public System.DateTime Fecha_registro
		{
			get
			{
				return this._Fecha_registro;
			}
			set
			{
				if ((this._Fecha_registro != value))
				{
					this.OnFecha_registroChanging(value);
					this.SendPropertyChanging();
					this._Fecha_registro = value;
					this.SendPropertyChanged("Fecha_registro");
					this.OnFecha_registroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_Producto")]
	public partial class Tipo_Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Tipo;
		
		private System.Nullable<System.DateTime> _FechaInserta;
		
		private string _UsuarioInserta;
		
		private System.Nullable<System.DateTime> _FechaActualiza;
		
		private string _UsuarioActualiza;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnFechaInsertaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaInsertaChanged();
    partial void OnUsuarioInsertaChanging(string value);
    partial void OnUsuarioInsertaChanged();
    partial void OnFechaActualizaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaActualizaChanged();
    partial void OnUsuarioActualizaChanging(string value);
    partial void OnUsuarioActualizaChanged();
    #endregion
		
		public Tipo_Producto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInserta", DbType="Date")]
		public System.Nullable<System.DateTime> FechaInserta
		{
			get
			{
				return this._FechaInserta;
			}
			set
			{
				if ((this._FechaInserta != value))
				{
					this.OnFechaInsertaChanging(value);
					this.SendPropertyChanging();
					this._FechaInserta = value;
					this.SendPropertyChanged("FechaInserta");
					this.OnFechaInsertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioInserta", DbType="VarChar(50)")]
		public string UsuarioInserta
		{
			get
			{
				return this._UsuarioInserta;
			}
			set
			{
				if ((this._UsuarioInserta != value))
				{
					this.OnUsuarioInsertaChanging(value);
					this.SendPropertyChanging();
					this._UsuarioInserta = value;
					this.SendPropertyChanged("UsuarioInserta");
					this.OnUsuarioInsertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualiza", DbType="Date")]
		public System.Nullable<System.DateTime> FechaActualiza
		{
			get
			{
				return this._FechaActualiza;
			}
			set
			{
				if ((this._FechaActualiza != value))
				{
					this.OnFechaActualizaChanging(value);
					this.SendPropertyChanging();
					this._FechaActualiza = value;
					this.SendPropertyChanged("FechaActualiza");
					this.OnFechaActualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioActualiza", DbType="VarChar(50)")]
		public string UsuarioActualiza
		{
			get
			{
				return this._UsuarioActualiza;
			}
			set
			{
				if ((this._UsuarioActualiza != value))
				{
					this.OnUsuarioActualizaChanging(value);
					this.SendPropertyChanging();
					this._UsuarioActualiza = value;
					this.SendPropertyChanged("UsuarioActualiza");
					this.OnUsuarioActualizaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorias")]
	public partial class Categorias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Nombre;
		
		private System.Nullable<System.DateTime> _FechaInserta;
		
		private string _UsuarioInserta;
		
		private System.Nullable<System.DateTime> _FechaActualiza;
		
		private string _UsuarioActualiza;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFechaInsertaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaInsertaChanged();
    partial void OnUsuarioInsertaChanging(string value);
    partial void OnUsuarioInsertaChanged();
    partial void OnFechaActualizaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaActualizaChanged();
    partial void OnUsuarioActualizaChanging(string value);
    partial void OnUsuarioActualizaChanged();
    #endregion
		
		public Categorias()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInserta", DbType="Date")]
		public System.Nullable<System.DateTime> FechaInserta
		{
			get
			{
				return this._FechaInserta;
			}
			set
			{
				if ((this._FechaInserta != value))
				{
					this.OnFechaInsertaChanging(value);
					this.SendPropertyChanging();
					this._FechaInserta = value;
					this.SendPropertyChanged("FechaInserta");
					this.OnFechaInsertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioInserta", DbType="VarChar(50)")]
		public string UsuarioInserta
		{
			get
			{
				return this._UsuarioInserta;
			}
			set
			{
				if ((this._UsuarioInserta != value))
				{
					this.OnUsuarioInsertaChanging(value);
					this.SendPropertyChanging();
					this._UsuarioInserta = value;
					this.SendPropertyChanged("UsuarioInserta");
					this.OnUsuarioInsertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualiza", DbType="Date")]
		public System.Nullable<System.DateTime> FechaActualiza
		{
			get
			{
				return this._FechaActualiza;
			}
			set
			{
				if ((this._FechaActualiza != value))
				{
					this.OnFechaActualizaChanging(value);
					this.SendPropertyChanging();
					this._FechaActualiza = value;
					this.SendPropertyChanged("FechaActualiza");
					this.OnFechaActualizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioActualiza", DbType="VarChar(50)")]
		public string UsuarioActualiza
		{
			get
			{
				return this._UsuarioActualiza;
			}
			set
			{
				if ((this._UsuarioActualiza != value))
				{
					this.OnUsuarioActualizaChanging(value);
					this.SendPropertyChanging();
					this._UsuarioActualiza = value;
					this.SendPropertyChanged("UsuarioActualiza");
					this.OnUsuarioActualizaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estados_Periodo")]
	public partial class Estados_Periodo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public Estados_Periodo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_modificar_usuarioResult
	{
		
		private string _Mensaje;
		
		public SP_modificar_usuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
