<?xml version="1.0" encoding="utf-8"?><Database Name="innguz_ventas" Class="Base_DatosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=innguz_ventas;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="innguz_ventasConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categorias" Member="Categorias">
    <Type Name="Categorias">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaInserta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioInserta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaActualiza" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioActualiza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Categorias_Productos" Member="Productos" ThisKey="id" OtherKey="Categoria_Id" Type="Productos" />
    </Type>
  </Table>
  <Table Name="dbo.Estados_Periodo" Member="Estados_Periodo">
    <Type Name="Estados_Periodo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Association Name="Estados_Periodo_Periodos" Member="Periodos" ThisKey="id" OtherKey="estado" Type="Periodos" />
    </Type>
  </Table>
  <Table Name="dbo.Periodos" Member="Periodos">
    <Type Name="Periodos">
      <Column Name="id_periodo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="año" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Periodos_Ventas" Member="Ventas" ThisKey="id_periodo" OtherKey="periodo_id" Type="Ventas" />
      <Association Name="Estados_Periodo_Periodos" Member="Estados_Periodo" ThisKey="estado" OtherKey="id" Type="Estados_Periodo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Productos" Member="Productos">
    <Type Name="Productos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripción" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="Tipo_Producto_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Categoria_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaInserta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioInserta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaActualiza" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioActualiza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Productos_Ventas" Member="Ventas" ThisKey="id" OtherKey="Producto_Servicio_id" Type="Ventas" />
      <Association Name="Categorias_Productos" Member="Categorias" ThisKey="Categoria_Id" OtherKey="id" Type="Categorias" IsForeignKey="true" />
      <Association Name="Tipo_Producto_Productos" Member="Tipo_Producto" ThisKey="Tipo_Producto_Id" OtherKey="id" Type="Tipo_Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tipo_Producto" Member="Tipo_Producto">
    <Type Name="Tipo_Producto">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaInserta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioInserta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaActualiza" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioActualiza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Tipo_Producto_Productos" Member="Productos" ThisKey="id" OtherKey="Tipo_Producto_Id" Type="Productos" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Posicion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_registro" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Usuarios_Ventas" Member="Ventas" ThisKey="Id" OtherKey="Usuario_id" Type="Ventas" />
    </Type>
  </Table>
  <Table Name="dbo.Ventas" Member="Ventas">
    <Type Name="Ventas">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="IVA" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="Usuario_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Producto_Servicio_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaInserta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioInserta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaActualiza" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioActualiza" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="periodo_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Periodos_Ventas" Member="Periodos" ThisKey="periodo_id" OtherKey="id_periodo" Type="Periodos" IsForeignKey="true" />
      <Association Name="Productos_Ventas" Member="Productos" ThisKey="Producto_Servicio_id" OtherKey="id" Type="Productos" IsForeignKey="true" />
      <Association Name="Usuarios_Ventas" Member="Usuarios" ThisKey="Usuario_id" OtherKey="Id" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
</Database>